// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnYc4Qh_ywl_4kXWJ0f_t0n1Z_ZImSKoI',
    appId: '1:814357705732:web:ec7418938ee0d487ce3151',
    messagingSenderId: '814357705732',
    projectId: 'cookius-40eb6',
    authDomain: 'cookius-40eb6.firebaseapp.com',
    databaseURL: 'https://cookius-40eb6-default-rtdb.firebaseio.com',
    storageBucket: 'cookius-40eb6.appspot.com',
    measurementId: 'G-QHJ056CRYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB3MY30wppvq0_Msotj3VwITILs9-CKwg',
    appId: '1:814357705732:android:c9439c804bdb922dce3151',
    messagingSenderId: '814357705732',
    projectId: 'cookius-40eb6',
    databaseURL: 'https://cookius-40eb6-default-rtdb.firebaseio.com',
    storageBucket: 'cookius-40eb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_eMcQ2rnu3XG7C2M66RZEz4FWJ-gmsc4',
    appId: '1:814357705732:ios:407db87a19a1d064ce3151',
    messagingSenderId: '814357705732',
    projectId: 'cookius-40eb6',
    databaseURL: 'https://cookius-40eb6-default-rtdb.firebaseio.com',
    storageBucket: 'cookius-40eb6.appspot.com',
    iosBundleId: 'com.example.cookiusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_eMcQ2rnu3XG7C2M66RZEz4FWJ-gmsc4',
    appId: '1:814357705732:ios:407db87a19a1d064ce3151',
    messagingSenderId: '814357705732',
    projectId: 'cookius-40eb6',
    databaseURL: 'https://cookius-40eb6-default-rtdb.firebaseio.com',
    storageBucket: 'cookius-40eb6.appspot.com',
    iosBundleId: 'com.example.cookiusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnYc4Qh_ywl_4kXWJ0f_t0n1Z_ZImSKoI',
    appId: '1:814357705732:web:c72f36983ade18a0ce3151',
    messagingSenderId: '814357705732',
    projectId: 'cookius-40eb6',
    authDomain: 'cookius-40eb6.firebaseapp.com',
    databaseURL: 'https://cookius-40eb6-default-rtdb.firebaseio.com',
    storageBucket: 'cookius-40eb6.appspot.com',
    measurementId: 'G-RL3CKWNQZF',
  );
}
